export const questions = {
    lessson1_Part1: [
        { 
            question: "What is the sign for the letter A?",
answerOptions: [
    { video:"/video/Basic/Lesson1/F.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/J.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/A.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/Q.mp4", isCorrect: false },
],
},
{ question: "What is the sign for the letter B?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/X.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/B.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/L.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/M.mp4", isCorrect: false },  
    ],
},
{ question: "What is the handshape for the letter C?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/G.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/A.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/C.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/P.mp4", isCorrect: false },  
    ],
},
{ question: "How do you form the letter D in sign language?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/T.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/D.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/Y.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/O.mp4", isCorrect: false },  
    ],
},
{ question: "What is the sign of the letter E?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/C.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/W.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/E.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/K.mp4", isCorrect: false },  
    ],
},
{ question: "What is the sign of the letter F?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/F.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/V.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/D.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/C.mp4", isCorrect: false },  
    ],
},
{ question: "How do you sign the letter G?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/R.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/X.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/B.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/G.mp4", isCorrect: true },  
    ],
},
{ question: "How do you sign the letter H?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/H.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/N.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/J.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/U.mp4", isCorrect: false },  
    ],
},
{ question: "How do you sign the letter I?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/Q.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/I.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/M.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/S.mp4", isCorrect: false },  
    ],
},
{ question: "How do you sign the letter J?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/J.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/L.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/E.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/D.mp4", isCorrect: false },  
    ],
},
{ question: "What is the sign of the letter K?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/W.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/K.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/Y.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/F.mp4", isCorrect: false },  
    ],
},
{ question: "How do you sign the letter L?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/P.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/L.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/R.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/Z.mp4", isCorrect: false },  
    ],
},
{ question: "How do you sign the letter M?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/M.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/X.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/A.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/U.mp4", isCorrect: false },  
    ],
},
{ question: "What is the sign for the letter N?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/C.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/N.mp4", isCorrect: true },
    { video:"/video/Basic/Lesson1/V.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/G.mp4", isCorrect: false },  
    ],
},
{ question: "What is the sign for the letter N?",
    answerOptions: [
    { video:"/video/Basic/Lesson1/S.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/K.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/H.mp4", isCorrect: false },
    { video:"/video/Basic/Lesson1/O.mp4", isCorrect: true },  
    ],
},
    ],
    lessson2_Part2: [
        { question: "How do you sign the letter P?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/D.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Y.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/P.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/X.mp4", isCorrect: false },  
            ],
        },
        { question: "What is the sign of the letter Q?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/Q.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/T.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/U.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/A.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter R?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/E.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/F.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/B.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/R.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter S?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/G.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Q.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/S.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/V.mp4", isCorrect: false },  
            ],
        },
        { question: "What is the sign of the letter T?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/Z.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/M.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/T.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/W.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter U?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/U.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/J.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Y.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/K.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter V?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/D.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/F.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/V.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/L.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter W?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/W.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/H.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/X.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/N.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter X?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/B.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/X.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/O.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/T.mp4", isCorrect: false },  
            ],
        },
        { question: "How do you sign the letter Y?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/P.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Y.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/R.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/A.mp4", isCorrect: false },  
            ],
        },
        { question: "What is the sign for the letter Z?",
            answerOptions: [
            { video:"/video/Basic/Lesson1/C.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/J.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/W.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Z.mp4", isCorrect: true },  
            ],
        },
        { question: "How do you sign \"Hello\"?",   
            answerOptions: [
            { video:"/video/Basic/Lesson1/C.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/World.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Hello.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/Z.mp4", isCorrect: false },    
            ],
        },  
        { question: "How do you sign \"World\"?",   
            answerOptions: [
            { video:"/video/Basic/Lesson1/Morning.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/World.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/Hello.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/A.mp4", isCorrect: false },    
            ],
        },  
        { question: "How do you sign \"Morning\"?",   
            answerOptions: [
            { video:"/video/Basic/Lesson1/Goodnight.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Hello.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Morning.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/World.mp4", isCorrect: false },    
            ],
        },  
        { question: "How do you sign \"Goodnight\"?",   
            answerOptions: [
            { video:"/video/Basic/Lesson1/Goodnight.mp4", isCorrect: true },
            { video:"/video/Basic/Lesson1/Hello.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/Morning.mp4", isCorrect: false },
            { video:"/video/Basic/Lesson1/World.mp4", isCorrect: false },    
            ],
        },  
        
    ]
}